# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_carrier', models.CharField(max_length=2)),
                ('fl_num', models.PositiveSmallIntegerField()),
                ('origin', models.CharField(max_length=3)),
                ('dest', models.CharField(max_length=3)),
                ('OTR', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HiddenFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('fl_date', models.DateTimeField()),
                ('carrier', models.CharField(max_length=2)),
                ('origin_airport_id', models.PositiveIntegerField()),
                ('dest_airport_id', models.PositiveIntegerField()),
                ('dep_delay_new', models.PositiveSmallIntegerField()),
                ('arr_delay_new', models.PositiveSmallIntegerField()),
                ('cancelled', models.PositiveSmallIntegerField()),
                ('diverted', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
