# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_carrier', models.CharField(max_length=2)),
                ('fl_num', models.PositiveSmallIntegerField()),
                ('origin', models.CharField(max_length=3)),
                ('dest', models.CharField(max_length=3)),
                ('OTR', models.PositiveSmallIntegerField()),
                ('scheduled_departure_time', models.PositiveSmallIntegerField()),
                ('scheduled_arrival_time', models.PositiveSmallIntegerField()),
                ('n', models.PositiveSmallIntegerField(default=0)),
                ('x', models.PositiveIntegerField(default=0)),
                ('c', models.PositiveSmallIntegerField(default=0)),
                ('Y', models.DecimalField(decimal_places=2, default=-1, max_digits=10)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl_date', models.DateTimeField()),
                ('carrier', models.CharField(max_length=2)),
                ('origin_airport_id', models.PositiveIntegerField()),
                ('dest_airport_id', models.PositiveIntegerField()),
                ('dep_delay_new', models.PositiveSmallIntegerField()),
                ('arr_delay_new', models.PositiveSmallIntegerField()),
                ('cancelled', models.PositiveSmallIntegerField()),
                ('diverted', models.PositiveSmallIntegerField()),
                ('unique_carrier', models.CharField(max_length=2)),
                ('fl_num', models.PositiveSmallIntegerField()),
                ('origin', models.CharField(max_length=3)),
                ('dest', models.CharField(max_length=3)),
                ('OTR', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
