# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20170612_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_carrier', models.CharField(max_length=2)),
                ('fl_num', models.PositiveSmallIntegerField()),
                ('origin', models.CharField(max_length=3)),
                ('dest', models.CharField(max_length=3)),
                ('OTR', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='month',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='year',
        ),
    ]
