# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20170619_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayflight',
            name='scheduled_arrival_time',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='displayflight',
            name='scheduled_departure_time',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
